### ISSUE TITLE
[Bug] <Add & Configure vite in ```Mini-Projects/Appline Website Clone```>

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/Mini-Projects#4]
### Description

- [ ]  Add & Configure vite

**Comment by sammaji** [comment]
`vite.config.js` is not required for vanilla js projects. just add a build script and a preview script

**Comment by sammaji** [comment]
Now you can deploy your app

**Comment by Arindam200** [comment]
@samyabrata-maji Thanks a lot!
